input.onButtonPressed(Button.A, function () {
    serial.writeLine("do you be friend of microbit? You have 5 seconds")
    basic.pause(5000)
    if (input.buttonIsPressed(Button.B)) {
        serial.writeLine("yes")
        for (let index = 0; index < 4; index++) {
            basic.showIcon(IconNames.Heart)
            basic.showIcon(IconNames.SmallHeart)
        }
        serial.writeLine("wow. thanks")
        basic.pause(500)
        serial.writeLine("Your welcome")
        basic.pause(500)
        serial.writeLine("ok, GoodLuck")
        basic.pause(500)
        serial.writeLine("you to")
        basic.pause(500)
        control.reset()
    } else if (input.buttonIsPressed(Button.A)) {
        serial.writeLine("no")
        basic.showIcon(IconNames.Sad)
        basic.pause(1000)
        serial.writeLine("Oh, why?")
        basic.pause(500)
        serial.writeLine("Because")
        basic.pause(500)
        serial.writeLine("oh, ok when bye")
        basic.pause(500)
        serial.writeLine("ok")
        basic.pause(500)
        control.reset()
    }
})
input.onGesture(Gesture.Shake, function () {
    basic.showIcon(IconNames.Surprised)
    serial.writeLine("why all is shaking?!")
    basic.pause(1000)
    serial.writeLine("oh its you")
    basic.pause(100)
    basic.showIcon(IconNames.Happy)
    basic.pause(1000)
    serial.writeLine("you want to be friends?")
})
serial.writeString("to be friends press P0")
basic.showIcon(IconNames.Asleep)
